git:
  depth: 3

language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode6.4
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode9.2

before_install: brew update

install:
  - brew install --build-bottle python35.rb
  - brew bottle --force-core-tap python35

after_success: curl --upload-file python*bottle* https://transfer.sh/
